name: build_test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Setting up .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restoring dependencies
      run: dotnet restore
    - name: Building the app
      run: dotnet build --no-restore
    - name: Running the tests
      run: dotnet test --no-build --verbosity normal
